# Generated by Django 3.1.3 on 2020-11-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_remove_form_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='description',
            field=models.TextField(default='everything'),
            preserve_default=False,
        ),
    ]
