# Generated by Django 3.1.3 on 2020-11-25 18:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_form_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
