# Generated by Django 3.1.3 on 2020-11-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_form_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='type',
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[(1, 'RadioButton'), (2, 'MultiChoice'), (3, 'Text')], default='RadioButton', max_length=100),
            preserve_default=False,
        ),
    ]
