# Generated by Django 3.1.3 on 2020-11-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20201125_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('RadioButton', 'RadioButton'), ('MultiChoice', 'MultiChoice'), ('Text', 'Text')], default='RadioButton', max_length=100),
        ),
    ]
